if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(CODE_PATH "/home/inmove/code/third_party_debug")
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
  set(CODE_PATH "/home/inmove/code/third_party")
endif()
set(OPENCV_DIR "${CODE_PATH}/opencv")
set(GOOGLE_TEST_DIR "${CODE_PATH}/googletest")
set(SPDLOG_DIR "${CODE_PATH}/spdlog")
set(YAML_CPP_DIR "${CODE_PATH}/yaml-cpp")
